export const FETCH_REPOSITORIES = "FETCH_REPOSITORIES";
export const LOAD_REPOSITORIES = "LOAD_REPOSITORIES";
export const FETCH_USER = "FETCH_USER";
export const SEARCH_LOADING = "SEARCH_LOADING";
export const USER_LOADING = "USER_LOADING";
export const ERROR = "ERROR";
